@startuml

title Sequence Diagram - Dependency Risk Analysis (Level 3)
skinparam monochrome true
skinparam shadowing false

actor User
participant "CLI" as CLI <<CLI>>
participant "AnalysisController" as CTRL <<Controllers>>
participant "DepcheckAdapter" as DEP <<Adapters>>
participant "DirtyWatersAdapter" as DW <<Adapters>>
participant "DependencySnifferAdapter" as DS <<Adapters>>
participant "SnykAdapter" as SS <<Adapters>>

participant "DepcheckService" as SD <<Services>>
participant "DirtyWatersService" as SDW <<Services>>
participant "DependencySniffersService" as SDS <<Services>>
participant "SnykService" as SSS <<Services>>

participant "DependencyService" as DepSer <<Services>>

participant "Dependency" as DEPDOM <<domain>>

participant "ReportGenerator" as Report <<Report>>
participant "ReportWriter" as ReportW <<Report>>

User -> CLI : executeCommand("dependencyTool analyze")
activate CLI

CLI -> CLI : buildCommand()
CLI -> CTRL : executeAnalysis(command)
activate CTRL

CTRL -> DepSer : extract_from_package_json(project_path)
activate DepSer

DepSer -> DEPDOM : add(dependency)
    activate DEPDOM

DEPDOM -> DepSer : dependency
    deactivate DEPDOM

DepSer --> CTRL: dependencies
deactivate DepSer

CTRL -> DEP : analyze(project_path)
activate DEP
DEP --> CTRL : depcheck_output
deactivate DEP

CTRL -> SD : map_results(depcheck_output, dependencies)
activate SD
SD --> CTRL : depcheck_results
deactivate SD

CTRL -> DS : analyze(project_path)
activate DS
DS --> CTRL : dependencySnifferResults
deactivate DS

CTRL -> SDS : analyze_constraints(sniffer_raw)
activate SDS
SDS --> CTRL : sniffer_results
deactivate SDS


CTRL -> SS : analyze(project_path)
activate SS

SS --> CTRL : snykResults
deactivate SS

CTRL -> SSS : analyze(snyk_raw)
activate SSS
SSS --> CTRL : snyk_results
deactivate SSS

CTRL -> DW : analyze(project_repo)
activate DW
DW --> CTRL : dirtyWatersResults
deactivate DW

CTRL -> SDW : analyze(dirty_waters_report)
activate SDW
SDW --> CTRL : dirty_waters_results
deactivate SDW


CTRL -> Report : generate_full_report(depcheck_results, sniffer_results, snyk_results, dirty_waters_results, dependencies, github_repo)
activate Report

Report --> CTRL : fullReport
deactivate Report

CTRL -> ReportW : save(report, report_path)
activate ReportW

ReportW --> CTRL : report
deactivate ReportW

CTRL --> CLI : report
deactivate CTRL

CLI --> User : report
deactivate CLI

@enduml