@startuml

title Sequence Diagram - Dependency Risk Analysis (Level 2)
skinparam monochrome true
skinparam shadowing false

actor User
participant "CLI" as CLI <<component>>
participant "Controllers" as CTRL <<component>>
participant "Adapters" as Adapters <<component>>
participant "Services" as SRV <<component>>
participant "Domain" as DOM <<component>>
participant "Report" as Report <<component>>

User -> CLI : run analysis command
activate CLI

CLI -> CTRL : command analysis
activate CTRL

CTRL -> Adapters : execute adapters (depcheck, dirty-waters, dependencySniffer, snyk)
activate Adapters

Adapters --> CTRL : adapters
deactivate Adapters

CTRL -> SRV : filter the information that the tool provide
activate SRV

SRV -> DOM : process domain logic
activate DOM
DOM --> SRV : Analysis Result
deactivate DOM

SRV --> CTRL : information for the Report
deactivate SRV

CTRL -> Report : generate report
activate Report

Report --> CTRL : formatted report
deactivate Report

CTRL --> CLI : response
deactivate CTRL

CLI --> User : display report
deactivate CLI

@enduml